version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=hello.settings
    volumes:
      - .:/app
    command: gunicorn hello.wsgi:application --bind 0.0.0.0:8000
